version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receitas-php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_DATE_TIMEZONE=America/Sao_Paulo
    networks:
      - receitas-network

networks:
  receitas-network:
    driver: bridge
